import Container from '../ui/Container';
import SectionHeading from '../ui/SectionHeading';

const stats = [
  { value: "19+", label: "Years Of Experience Field" },
  { value: "200+", label: "Projects Impact With Innovative" },
  { value: "300+", label: "Agro Tech Company Have Grown Here" },
  { value: "$15 Million", label: "Revenue Generated By Our Services" },
];

export default function Stats() {
  return (
    <section className="pt-24 bg-background border-b border-gray-100">
      <Container>
        <div className="flex flex-col lg:flex-row justify-between lg:items-end gap-8 mb-16">
          <SectionHeading
            pill="Our Achievements"
            title="The Relentless Efforts And Achievements Of Our Farmers"
          />
          <p className="text-gray-600 max-w-md text-lg">
            Whether through mentorship or advising  use or implementing new practices, their spirit inspires us to keep pushing limits and achieving more.
          </p>
        </div>
        
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-12 lg:gap-8 divide-x-0 sm:divide-x-0 lg:divide-x divide-gray-200">
          {stats.map((stat, idx) => (
            <div key={idx} className={`flex flex-col gap-2 ${idx !== 0 ? 'lg:pl-8' : ''}`}>
              <div className="text-5xl text-center md:text-start md:text-6xl font-bold text-foreground">{stat.value}</div>
              <p className="text-gray-600 font-medium text-lg text-center md:text-start md:max-w-50 leading-snug">{stat.label}</p>
            </div>
          ))}
        </div>
      </Container>
    </section>
  );
}
